[TASK] Update workflow

diff --git a/.github/workflows/eslint.yml b/.github/workflows/eslint.yml
--- a/.github/workflows/eslint.yml
+++ b/.github/workflows/eslint.yml
@@ -41,7 +41,7 @@ jobs:
       # Step 5: Run ESLint for JavaScript
       - name: Run ESLint
         run: |
-          npx eslint assets/js/ || (echo "ESLint check failed. Please fix the issues before pushing the code." && exit 1)
+          npx eslint src/js/ || (echo "ESLint check failed. Please fix the issues before pushing the code." && exit 1)
 
   # Stage 2: Lint HTML
   lint_html:
@@ -75,11 +75,11 @@ jobs:
       # Step 5: Run HTMLHint for HTML
       - name: Run HTMLHint
         run: |
-          npx htmlhint assets/*.html || (echo "HTMLHint check failed. Please fix the issues before pushing the code." && exit 1)
+          npx htmlhint src/html/*.html || (echo "HTMLHint check failed. Please fix the issues before pushing the code." && exit 1)
 
-  # Stage 3: Lint CSS
-  lint_css:
-    name: Lint CSS
+  # Stage 3: Lint SCSS
+  lint_scss:
+    name: Lint SCSS
     runs-on: ubuntu-latest
 
     steps:
@@ -104,9 +104,9 @@ jobs:
 
       # Step 4: Install Stylelint
       - name: Install Stylelint
-        run:  npm install -g eslint stylelint stylelint-config-standard
+        run: npm install -g eslint stylelint stylelint-config-standard-scss
 
-      # Step 5: Run Stylelint for CSS
+      # Step 5: Run Stylelint for SCSS
       - name: Run Stylelint
         run: |
-          npx stylelint assets/css/*.css || (echo "Stylelint check failed. Please fix the issues before pushing the code." && exit 1)
+          npx stylelint src/scss/*.scss || (echo "Stylelint check failed. Please fix the issues before pushing the code." && exit 1)
