[TASK] Update workflow

diff --git a/.github/workflows/eslint.yml b/.github/workflows/eslint.yml
--- a/.github/workflows/eslint.yml
+++ b/.github/workflows/eslint.yml
@@ -20,11 +20,10 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '20' # Updated to Node.js version 20
+          node-version: '20'
 
-      - name: Install dependencies
-        run: npm install
+      - name: Install ESLint
+        run: npm install -g eslint # Install ESLint globally
 
       - name: Run ESLint
-        run: |
-          npx eslint . || (echo "ESLint check failed. Please fix the issues before pushing the code." && exit 1)
+        run: npx eslint assets/js/ || (echo "ESLint check failed. Please fix the issues before pushing the code." && exit 1)
