[TASK] Worked on #13 (#15)
Set up Webpack and PostCSS build system for Quick helper chrome extension

diff --git a/.github/workflows/eslint.yml b/.github/workflows/eslint.yml
--- a/.github/workflows/eslint.yml
+++ b/.github/workflows/eslint.yml
@@ -34,14 +34,14 @@ jobs:
         with:
           node-version: '20'
 
-      # Step 4: Install ESLint
-      - name: Install ESLint
-        run: npm install -g eslint
+      # Step 4: Install dependencies
+      - name: Install dependencies
+        run: npm install
 
       # Step 5: Run ESLint for JavaScript
       - name: Run ESLint
         run: |
-          npx eslint assets/js/ || (echo "ESLint check failed. Please fix the issues before pushing the code." && exit 1)
+          npx eslint src/js/ || (echo "ESLint check failed. Please fix the issues before pushing the code." && exit 1)
 
   # Stage 2: Lint HTML
   lint_html:
@@ -68,14 +68,14 @@ jobs:
         with:
           node-version: '20'
 
-      # Step 4: Install HTMLHint
-      - name: Install HTMLHint
-        run: npm install -g htmlhint
+      # Step 4: Install dependencies
+      - name: Install dependencies
+        run: npm install
 
       # Step 5: Run HTMLHint for HTML
       - name: Run HTMLHint
         run: |
-          npx htmlhint assets/*.html || (echo "HTMLHint check failed. Please fix the issues before pushing the code." && exit 1)
+          npx htmlhint src/html/*.html || (echo "HTMLHint check failed. Please fix the issues before pushing the code." && exit 1)
 
   # Stage 3: Lint CSS
   lint_css:
@@ -102,11 +102,11 @@ jobs:
         with:
           node-version: '20'
 
-      # Step 4: Install Stylelint
-      - name: Install Stylelint
-        run:  npm install -g eslint stylelint stylelint-config-standard
+      # Step 4: Install dependencies
+      - name: Install dependencies
+        run: npm install
 
-      # Step 5: Run Stylelint for CSS
+      # Step 5: Run Stylelint for SCSS
       - name: Run Stylelint
         run: |
-          npx stylelint assets/css/*.css || (echo "Stylelint check failed. Please fix the issues before pushing the code." && exit 1)
+          npx stylelint src/scss/**/*.scss || (echo "Stylelint check failed. Please fix the issues before pushing the code." && exit 1)
