Update eslint.yml

diff --git a/.github/workflows/eslint.yml b/.github/workflows/eslint.yml
--- a/.github/workflows/eslint.yml
+++ b/.github/workflows/eslint.yml
@@ -20,14 +20,11 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '16'
+          node-version: '20' # Updated to Node.js version 20
 
       - name: Install dependencies
         run: npm install
 
       - name: Run ESLint
-        run: npx eslint . # Lint all files in the repo
-
-      - name: Fail the job on ESLint error
-        if: failure()
-        run: echo "ESLint check failed. Please fix the issues before pushing the code."
+        run: |
+          npx eslint . || (echo "ESLint check failed. Please fix the issues before pushing the code." && exit 1)
